spring:
  application:
    name: devhub

  datasource:
    url: jdbc:mysql://120.53.225.128:3306/devhub
    username: root
    password: LinCong@2025
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  configuration:
    # 开启驼峰映射
    map-underscore-to-camel-case: true