spring:
  application:
    name: devhub

  datasource:
    # 启动时从环境变量读取数据库连接信息
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  configuration:
    # 开启驼峰映射
    map-underscore-to-camel-case: true